# Generated by Django 3.0.3 on 2020-03-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(max_length=20),
        ),
    ]
