# Generated by Django 3.0.3 on 2020-08-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200322_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatar/default_avatar.png', upload_to='profile_avatar'),
        ),
    ]
