# Generated by Django 3.0.3 on 2021-01-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='related_skill',
        ),
    ]
