# Generated by Django 3.0.3 on 2021-01-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210120_1639'),
        ('projects', '0005_auto_20210121_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(to='accounts.Skill'),
        ),
    ]
