# Generated by Django 3.0.3 on 2021-01-26 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_position_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL)),
                ('applications_list', models.ManyToManyField(blank=True, related_name='applications_list', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.Position')),
            ],
            options={
                'unique_together': {('acceptor', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
