# Generated by Django 3.0.3 on 2021-02-01 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210128_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position_title']},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='description',
            new_name='position_description',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='position_title',
        ),
        migrations.AddField(
            model_name='position',
            name='project_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
