# Generated by Django 3.0.3 on 2021-02-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210131_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='project_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_set', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(related_name='projects', to='projects.Position'),
        ),
    ]
