# Generated by Django 3.0.3 on 2021-02-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210131_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=999999999, null=True),
        ),
    ]
