# Generated by Django 3.0.3 on 2021-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='applicationrequest',
            name='sender',
        ),
        migrations.AddField(
            model_name='position',
            name='application_status',
            field=models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending'), ('O', 'Open')], default='O', max_length=1),
        ),
        migrations.DeleteModel(
            name='ApplicationList',
        ),
        migrations.DeleteModel(
            name='ApplicationRequest',
        ),
    ]
