# Generated by Django 3.0.3 on 2021-02-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_auto_20210213_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='points',
        ),
        migrations.AlterField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(default=None, related_name='projects', to='projects.Position'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending'), ('O', 'Open')], default='O', max_length=1)),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Position')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
