# Generated by Django 3.0.3 on 2021-02-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210217_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Position'),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(default=None, null=True, related_name='projects', to='projects.Position'),
        ),
        migrations.DeleteModel(
            name='ProjectPosition',
        ),
    ]
