# Generated by Django 3.0.3 on 2021-02-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210217_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(default=None, related_name='projects', to='projects.Position'),
        ),
    ]
